[tool.poetry]
name = "bedrock-lambda-test"
version = "0.1.0"
description = ""
authors = ["x0x0b"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
boto3 = "^1.35.90"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
